#!/bin/sh
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#

echo "commit-msg ~"

# 命令执行路径在项目根目录
COMMIT_MSG_FILE=$1

HOOK_PATH=$(git config --local --get core.hooksPath)
python ${HOOK_PATH}/commit_msg.py "$COMMIT_MSG_FILE"